In [8]:
import torch

In [9]:
a = torch.arange(24).reshape(4, 6)
a

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [14]:
x, y, z = torch.split(a, 2, dim=-1)

In [15]:
x

tensor([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]])

In [16]:
y

tensor([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]])

In [17]:
z

tensor([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])